# ---------- Build stage ----------
FROM golang:1.25-alpine AS builder

WORKDIR /app

RUN apk add --no-cache ca-certificates

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -o /bin/iam-server ./cmd/grpc/iam


# ---------- Runtime stage ----------
FROM alpine:3.22

RUN apk add --no-cache ca-certificates

COPY --from=builder /bin/iam-server /bin/iam-server

ENTRYPOINT ["/bin/iam-server"]