# ---------- Build stage ----------
FROM golang:1.25-alpine AS builder

WORKDIR /app

RUN apk add --no-cache ca-certificates

# Cache Go dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy source
COPY . .

# Build Go media server
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -o /bin/media-server ./cmd/grpc/media


# ---------- Runtime stage ----------
FROM alpine:3.22

RUN apk add --no-cache ca-certificates

COPY --from=builder /bin/media-server /bin/media-server

ENTRYPOINT ["/bin/media-server"]