syntax="proto3";

option go_package = "github.com/lucas-woo/cloud-drive/api/iam/v1/iamv1";

package iam.v1;

import "google/protobuf/timestamp.proto";

//should implement being be able to create roles with certain priviledges
//upload priviledges, delete, activate/disactivate, generate api keys

message GenerateNewApiKeyRequest {
  string project_id = 1;
  string key_name = 2;
}

message GenerateNewApiKeyResponse {
  string api_key = 1;
  string api_secret = 2;
  google.protobuf.Timestamp created_at = 3; 
}

enum Permission {
  PERMISSION_STATUS_UNSPECIFIED = 0;
  PERMISSION_GET = 1;
  PERMISSION_CREATE = 2;
  PERMISSION_DELETE = 3;
}

message ValidateApiKeyPermissionRequest {
  string api_key = 1;
  string api_secret = 2;
  string project_id = 3;
  Permission permission = 4;
}

message ValidateApiKeyPermissionResponse {
  bool authorized = 1;
}

message AddUserRolePermissionRequest {
  enum Permission {
    PERMISSION_STATUS_UNSPECIFIED = 0;
    PERMISSION_ADMIN_ROLE = 1;
  }    
  string user_id = 1;
  string project_id = 2;
  Permission role = 3;
}

message AddUserRolePermissionResponse {
  bool updated = 1;
}

message ValidateUserPermissionRequest {
  enum Permission {
    PERMISSION_STATUS_UNSPECIFIED = 0;
    PERMISSION_ADMIN_ROLE = 1;
  }  
  string user_id = 1;
  string project_id = 2;
  Permission role = 3;
}

message ValidateUserPermissionResponse {
  bool authorized = 1;
}

message ApiKey {
  string api_key = 1;
  string key_name = 2;
  google.protobuf.Timestamp created_at = 3;
  bool is_active = 4;
}

message GetAllApiKeysRequest {
  string project_id = 1;
}

message GetAllApiKeysResponse {
  repeated ApiKey api_keys = 1;
}

message GetProjectIdRequest {
  string api_key = 1;
}

message GetProjectIdResponse {
  string project_id = 1;
}