syntax="proto3";

import "google/protobuf/timestamp.proto";

option go_package = "github.com/lucas-woo/cloud-drive/api/apikeys/v1/apikeysv1";

package apikeys.v1;

message UploadFileRequest {
  string session_id = 1;
  string project_id = 2;
  string folder_name = 3;
  //byte content ... 
  google.protobuf.Timestamp created_at = 4;
}

message UploadFileResponse {
  string session_id = 1;
  string url = 2;
}

message CreateNewProjectRequest {
  string session_id = 1;
  string project_id = 2;
  string folder_name = 3;
} 

message CreateNewProjectResponse {

}