syntax="proto3";

option go_package = "github.com/lucas-woo/cloud-drive/api/apikeys/v1/authv1";

package apikeys.v1;

import "apikeys/v1/apikeys.proto";

service ApiKeysService {
  //from api
  rpc ApiUploadImage(stream ApiUploadImageRequest) returns (ApiUploadImageResponse);
  rpc ApiUploadFile(ApiUploadFileRequest) returns(ApiUploadFileResponse);

  //from web
  rpc UploadImage(stream UploadImageRequest) returns (UploadImageResponse);
  rpc UploadFile(UploadFileRequest) returns(UploadFileResponse);  
  rpc GenerateNewApiKey() returns();
  rpc CreateNewProject() returns();
  rpc CreateNewFolder() returns();
  rpc DeactivateApiKey() returns();
  rpc ActivateApiKey() returns();
  rpc RenameKey() returns();
  rpc GetApiKeys() returns();
  rpc ViewApiSecret returns()
}