syntax="proto3";

option go_package = "github.com/lucas-woo/cloud-drive/api/apikeys/v1/authv1";

package apikeys.v1;

import "apikeys/v1/apikeys.proto";

service ApiKeysService {

  rpc UploadImage() returns ();
  rpc UploadFile() returns();
  rpc CreateNewProject() returns();
  rpc GenerateNewSecret() returns();
  rpc CreateNewFolder() returns();
  rpc DeactivateApiKey() returns();
  rpc ActivateApiKey() returns();
  rpc RenameKey() returns();
  rpc GetApiKeys() returns();
  rpc ViewApiSecret returns()
}