syntax="proto3";

option go_package = "github.com/lucas-woo/cloud-drive/api/media/v1/mediav1";

package media.v1;

import "media/v1/media.proto";

service MediaService {
  
  rpc CreateNewProject(CreateNewProjectRequest) returns (CreateNewProjectResponse);

  rpc UploadObject(UploadObjectRequest) returns (UploadObjectResponse);
  
  rpc UploadImageApi(stream UploadImageApiRequest) returns (UploadImageApiResponse);
  
  rpc UploadFileApi(stream UploadFileApiRequest) returns (UploadFileApiResponse);

  rpc ObjectUploadConfirmation(ObjectUploadConfirmationRequest) returns(ObjectUploadConfirmationResponse);

  rpc GetDashboard(GetDashboardRequest) returns(GetDashboardResponse);


  // rpc create new folder
  //rpc get folders
}