syntax="proto3";

option go_package = "github.com/lucas-woo/cloud-drive/api/media/v1/mediav1";

package media.v1;

import "media/v1/media.proto";

service MediaService {
  
  rpc CreateNewProject(CreateNewProjectRequest) returns (CreateNewProjectResponse);

  rpc UploadObject(UploadObjectRequest) returns (UploadObjectResponse);
  
  rpc UploadImageApi(stream UploadImageApiRequest) returns (UploadImageApiResponse);
  
  rpc UploadFileApi(stream UploadFileApiRequest) returns (UploadFileApiResponse);

  rpc ObjectUploadConfirmation(ObjectUploadConfirmationRequest) returns(ObjectUploadConfirmationResponse);

  //get image data by objectId : 
  //uploading file by api should just be returned a signedurl 
  //rpc ChangeProjectName()
}