// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: apikeys/v1/apikeys.proto

package apikeysv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateNewProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	FolderName    string                 `protobuf:"bytes,3,opt,name=folder_name,json=folderName,proto3" json:"folder_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNewProjectRequest) Reset() {
	*x = CreateNewProjectRequest{}
	mi := &file_apikeys_v1_apikeys_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewProjectRequest) ProtoMessage() {}

func (x *CreateNewProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apikeys_v1_apikeys_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateNewProjectRequest) Descriptor() ([]byte, []int) {
	return file_apikeys_v1_apikeys_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNewProjectRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateNewProjectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateNewProjectRequest) GetFolderName() string {
	if x != nil {
		return x.FolderName
	}
	return ""
}

type CreateNewProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNewProjectResponse) Reset() {
	*x = CreateNewProjectResponse{}
	mi := &file_apikeys_v1_apikeys_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewProjectResponse) ProtoMessage() {}

func (x *CreateNewProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apikeys_v1_apikeys_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewProjectResponse.ProtoReflect.Descriptor instead.
func (*CreateNewProjectResponse) Descriptor() ([]byte, []int) {
	return file_apikeys_v1_apikeys_proto_rawDescGZIP(), []int{1}
}

var File_apikeys_v1_apikeys_proto protoreflect.FileDescriptor

const file_apikeys_v1_apikeys_proto_rawDesc = "" +
	"\n" +
	"\x18apikeys/v1/apikeys.proto\x12\n" +
	"apikeys.v1\"x\n" +
	"\x17CreateNewProjectRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x1f\n" +
	"\vfolder_name\x18\x03 \x01(\tR\n" +
	"folderName\"\x1a\n" +
	"\x18CreateNewProjectResponseB;Z9github.com/lucas-woo/cloud-drive/api/apikeys/v1/apikeysv1b\x06proto3"

var (
	file_apikeys_v1_apikeys_proto_rawDescOnce sync.Once
	file_apikeys_v1_apikeys_proto_rawDescData []byte
)

func file_apikeys_v1_apikeys_proto_rawDescGZIP() []byte {
	file_apikeys_v1_apikeys_proto_rawDescOnce.Do(func() {
		file_apikeys_v1_apikeys_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apikeys_v1_apikeys_proto_rawDesc), len(file_apikeys_v1_apikeys_proto_rawDesc)))
	})
	return file_apikeys_v1_apikeys_proto_rawDescData
}

var file_apikeys_v1_apikeys_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_apikeys_v1_apikeys_proto_goTypes = []any{
	(*CreateNewProjectRequest)(nil),  // 0: apikeys.v1.CreateNewProjectRequest
	(*CreateNewProjectResponse)(nil), // 1: apikeys.v1.CreateNewProjectResponse
}
var file_apikeys_v1_apikeys_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apikeys_v1_apikeys_proto_init() }
func file_apikeys_v1_apikeys_proto_init() {
	if File_apikeys_v1_apikeys_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apikeys_v1_apikeys_proto_rawDesc), len(file_apikeys_v1_apikeys_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apikeys_v1_apikeys_proto_goTypes,
		DependencyIndexes: file_apikeys_v1_apikeys_proto_depIdxs,
		MessageInfos:      file_apikeys_v1_apikeys_proto_msgTypes,
	}.Build()
	File_apikeys_v1_apikeys_proto = out.File
	file_apikeys_v1_apikeys_proto_goTypes = nil
	file_apikeys_v1_apikeys_proto_depIdxs = nil
}
