// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: apikeys/v1/service.proto

package apikeysv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ApiKeysService_UploadFile_FullMethodName       = "/apikeys.v1.ApiKeysService/UploadFile"
	ApiKeysService_CreateNewProject_FullMethodName = "/apikeys.v1.ApiKeysService/CreateNewProject"
)

// ApiKeysServiceClient is the client API for ApiKeysService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApiKeysServiceClient interface {
	// implemented:
	UploadFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadFileRequest, UploadFileResponse], error)
	CreateNewProject(ctx context.Context, in *CreateNewProjectRequest, opts ...grpc.CallOption) (*CreateNewProjectResponse, error)
}

type apiKeysServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewApiKeysServiceClient(cc grpc.ClientConnInterface) ApiKeysServiceClient {
	return &apiKeysServiceClient{cc}
}

func (c *apiKeysServiceClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadFileRequest, UploadFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ApiKeysService_ServiceDesc.Streams[0], ApiKeysService_UploadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadFileRequest, UploadFileResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ApiKeysService_UploadFileClient = grpc.ClientStreamingClient[UploadFileRequest, UploadFileResponse]

func (c *apiKeysServiceClient) CreateNewProject(ctx context.Context, in *CreateNewProjectRequest, opts ...grpc.CallOption) (*CreateNewProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNewProjectResponse)
	err := c.cc.Invoke(ctx, ApiKeysService_CreateNewProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiKeysServiceServer is the server API for ApiKeysService service.
// All implementations must embed UnimplementedApiKeysServiceServer
// for forward compatibility.
type ApiKeysServiceServer interface {
	// implemented:
	UploadFile(grpc.ClientStreamingServer[UploadFileRequest, UploadFileResponse]) error
	CreateNewProject(context.Context, *CreateNewProjectRequest) (*CreateNewProjectResponse, error)
	mustEmbedUnimplementedApiKeysServiceServer()
}

// UnimplementedApiKeysServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApiKeysServiceServer struct{}

func (UnimplementedApiKeysServiceServer) UploadFile(grpc.ClientStreamingServer[UploadFileRequest, UploadFileResponse]) error {
	return status.Error(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedApiKeysServiceServer) CreateNewProject(context.Context, *CreateNewProjectRequest) (*CreateNewProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNewProject not implemented")
}
func (UnimplementedApiKeysServiceServer) mustEmbedUnimplementedApiKeysServiceServer() {}
func (UnimplementedApiKeysServiceServer) testEmbeddedByValue()                        {}

// UnsafeApiKeysServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiKeysServiceServer will
// result in compilation errors.
type UnsafeApiKeysServiceServer interface {
	mustEmbedUnimplementedApiKeysServiceServer()
}

func RegisterApiKeysServiceServer(s grpc.ServiceRegistrar, srv ApiKeysServiceServer) {
	// If the following call panics, it indicates UnimplementedApiKeysServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ApiKeysService_ServiceDesc, srv)
}

func _ApiKeysService_UploadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ApiKeysServiceServer).UploadFile(&grpc.GenericServerStream[UploadFileRequest, UploadFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ApiKeysService_UploadFileServer = grpc.ClientStreamingServer[UploadFileRequest, UploadFileResponse]

func _ApiKeysService_CreateNewProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNewProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiKeysServiceServer).CreateNewProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiKeysService_CreateNewProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiKeysServiceServer).CreateNewProject(ctx, req.(*CreateNewProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApiKeysService_ServiceDesc is the grpc.ServiceDesc for ApiKeysService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApiKeysService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apikeys.v1.ApiKeysService",
	HandlerType: (*ApiKeysServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNewProject",
			Handler:    _ApiKeysService_CreateNewProject_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadFile",
			Handler:       _ApiKeysService_UploadFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "apikeys/v1/service.proto",
}
