// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: apikeys/v1/service.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_apikeys_v1_service_proto protoreflect.FileDescriptor

const file_apikeys_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x18apikeys/v1/service.proto\x12\n" +
	"apikeys.v1\x1a\x18apikeys/v1/apikeys.proto2\xbe\x01\n" +
	"\x0eApiKeysService\x12M\n" +
	"\n" +
	"UploadFile\x12\x1d.apikeys.v1.UploadFileRequest\x1a\x1e.apikeys.v1.UploadFileResponse(\x01\x12]\n" +
	"\x10CreateNewProject\x12#.apikeys.v1.CreateNewProjectRequest\x1a$.apikeys.v1.CreateNewProjectResponseB8Z6github.com/lucas-woo/cloud-drive/api/apikeys/v1/authv1b\x06proto3"

var file_apikeys_v1_service_proto_goTypes = []any{
	(*UploadFileRequest)(nil),        // 0: apikeys.v1.UploadFileRequest
	(*CreateNewProjectRequest)(nil),  // 1: apikeys.v1.CreateNewProjectRequest
	(*UploadFileResponse)(nil),       // 2: apikeys.v1.UploadFileResponse
	(*CreateNewProjectResponse)(nil), // 3: apikeys.v1.CreateNewProjectResponse
}
var file_apikeys_v1_service_proto_depIdxs = []int32{
	0, // 0: apikeys.v1.ApiKeysService.UploadFile:input_type -> apikeys.v1.UploadFileRequest
	1, // 1: apikeys.v1.ApiKeysService.CreateNewProject:input_type -> apikeys.v1.CreateNewProjectRequest
	2, // 2: apikeys.v1.ApiKeysService.UploadFile:output_type -> apikeys.v1.UploadFileResponse
	3, // 3: apikeys.v1.ApiKeysService.CreateNewProject:output_type -> apikeys.v1.CreateNewProjectResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apikeys_v1_service_proto_init() }
func file_apikeys_v1_service_proto_init() {
	if File_apikeys_v1_service_proto != nil {
		return
	}
	file_apikeys_v1_apikeys_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apikeys_v1_service_proto_rawDesc), len(file_apikeys_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apikeys_v1_service_proto_goTypes,
		DependencyIndexes: file_apikeys_v1_service_proto_depIdxs,
	}.Build()
	File_apikeys_v1_service_proto = out.File
	file_apikeys_v1_service_proto_goTypes = nil
	file_apikeys_v1_service_proto_depIdxs = nil
}
