// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: media/v1/assets.proto

package mediav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssetCursor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ObjectId      string                 `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetCursor) Reset() {
	*x = AssetCursor{}
	mi := &file_media_v1_assets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetCursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetCursor) ProtoMessage() {}

func (x *AssetCursor) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_assets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetCursor.ProtoReflect.Descriptor instead.
func (*AssetCursor) Descriptor() ([]byte, []int) {
	return file_media_v1_assets_proto_rawDescGZIP(), []int{0}
}

func (x *AssetCursor) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AssetCursor) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

type ProjectFolder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolderId      string                 `protobuf:"bytes,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	FolderName    string                 `protobuf:"bytes,2,opt,name=folder_name,json=folderName,proto3" json:"folder_name,omitempty"`
	FolderSize    int64                  `protobuf:"varint,3,opt,name=folder_size,json=folderSize,proto3" json:"folder_size,omitempty"`
	AssetCount    int32                  `protobuf:"varint,4,opt,name=asset_count,json=assetCount,proto3" json:"asset_count,omitempty"`
	LastUplaod    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_uplaod,json=lastUplaod,proto3" json:"last_uplaod,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ModifiedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectFolder) Reset() {
	*x = ProjectFolder{}
	mi := &file_media_v1_assets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectFolder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectFolder) ProtoMessage() {}

func (x *ProjectFolder) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_assets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectFolder.ProtoReflect.Descriptor instead.
func (*ProjectFolder) Descriptor() ([]byte, []int) {
	return file_media_v1_assets_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectFolder) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

func (x *ProjectFolder) GetFolderName() string {
	if x != nil {
		return x.FolderName
	}
	return ""
}

func (x *ProjectFolder) GetFolderSize() int64 {
	if x != nil {
		return x.FolderSize
	}
	return 0
}

func (x *ProjectFolder) GetAssetCount() int32 {
	if x != nil {
		return x.AssetCount
	}
	return 0
}

func (x *ProjectFolder) GetLastUplaod() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUplaod
	}
	return nil
}

func (x *ProjectFolder) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProjectFolder) GetModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

type ProjectObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	CollectionId  string                 `protobuf:"bytes,2,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	FolderId      string                 `protobuf:"bytes,3,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	ObjectId      string                 `protobuf:"bytes,4,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	FileSize      int64                  `protobuf:"varint,5,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Format        string                 `protobuf:"bytes,6,opt,name=format,proto3" json:"format,omitempty"`
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ModifiedAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectObject) Reset() {
	*x = ProjectObject{}
	mi := &file_media_v1_assets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectObject) ProtoMessage() {}

func (x *ProjectObject) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_assets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectObject.ProtoReflect.Descriptor instead.
func (*ProjectObject) Descriptor() ([]byte, []int) {
	return file_media_v1_assets_proto_rawDescGZIP(), []int{2}
}

func (x *ProjectObject) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ProjectObject) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *ProjectObject) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

func (x *ProjectObject) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *ProjectObject) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *ProjectObject) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ProjectObject) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ProjectObject) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProjectObject) GetModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

type ProjectCollection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollectionId  string                 `protobuf:"bytes,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastModified  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	IsPublic      bool                   `protobuf:"varint,6,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectCollection) Reset() {
	*x = ProjectCollection{}
	mi := &file_media_v1_assets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectCollection) ProtoMessage() {}

func (x *ProjectCollection) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_assets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectCollection.ProtoReflect.Descriptor instead.
func (*ProjectCollection) Descriptor() ([]byte, []int) {
	return file_media_v1_assets_proto_rawDescGZIP(), []int{3}
}

func (x *ProjectCollection) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *ProjectCollection) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectCollection) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProjectCollection) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProjectCollection) GetLastModified() *timestamppb.Timestamp {
	if x != nil {
		return x.LastModified
	}
	return nil
}

func (x *ProjectCollection) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

var File_media_v1_assets_proto protoreflect.FileDescriptor

const file_media_v1_assets_proto_rawDesc = "" +
	"\n" +
	"\x15media/v1/assets.proto\x12\bmedia.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"e\n" +
	"\vAssetCursor\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1b\n" +
	"\tobject_id\x18\x02 \x01(\tR\bobjectId\"\xc4\x02\n" +
	"\rProjectFolder\x12\x1b\n" +
	"\tfolder_id\x18\x01 \x01(\tR\bfolderId\x12\x1f\n" +
	"\vfolder_name\x18\x02 \x01(\tR\n" +
	"folderName\x12\x1f\n" +
	"\vfolder_size\x18\x03 \x01(\x03R\n" +
	"folderSize\x12\x1f\n" +
	"\vasset_count\x18\x04 \x01(\x05R\n" +
	"assetCount\x12;\n" +
	"\vlast_uplaod\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUplaod\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\vmodified_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifiedAt\"\xd7\x02\n" +
	"\rProjectObject\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12#\n" +
	"\rcollection_id\x18\x02 \x01(\tR\fcollectionId\x12\x1b\n" +
	"\tfolder_id\x18\x03 \x01(\tR\bfolderId\x12\x1b\n" +
	"\tobject_id\x18\x04 \x01(\tR\bobjectId\x12\x1b\n" +
	"\tfile_size\x18\x05 \x01(\x03R\bfileSize\x12\x16\n" +
	"\x06format\x18\x06 \x01(\tR\x06format\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\vmodified_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifiedAt\"\x87\x02\n" +
	"\x11ProjectCollection\x12#\n" +
	"\rcollection_id\x18\x01 \x01(\tR\fcollectionId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12?\n" +
	"\rlast_modified\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\flastModified\x12\x1b\n" +
	"\tis_public\x18\x06 \x01(\bR\bisPublicB7Z5github.com/lucas-woo/cloud-drive/api/media/v1/mediav1b\x06proto3"

var (
	file_media_v1_assets_proto_rawDescOnce sync.Once
	file_media_v1_assets_proto_rawDescData []byte
)

func file_media_v1_assets_proto_rawDescGZIP() []byte {
	file_media_v1_assets_proto_rawDescOnce.Do(func() {
		file_media_v1_assets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_v1_assets_proto_rawDesc), len(file_media_v1_assets_proto_rawDesc)))
	})
	return file_media_v1_assets_proto_rawDescData
}

var file_media_v1_assets_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_media_v1_assets_proto_goTypes = []any{
	(*AssetCursor)(nil),           // 0: media.v1.AssetCursor
	(*ProjectFolder)(nil),         // 1: media.v1.ProjectFolder
	(*ProjectObject)(nil),         // 2: media.v1.ProjectObject
	(*ProjectCollection)(nil),     // 3: media.v1.ProjectCollection
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_media_v1_assets_proto_depIdxs = []int32{
	4, // 0: media.v1.AssetCursor.created_at:type_name -> google.protobuf.Timestamp
	4, // 1: media.v1.ProjectFolder.last_uplaod:type_name -> google.protobuf.Timestamp
	4, // 2: media.v1.ProjectFolder.created_at:type_name -> google.protobuf.Timestamp
	4, // 3: media.v1.ProjectFolder.modified_at:type_name -> google.protobuf.Timestamp
	4, // 4: media.v1.ProjectObject.created_at:type_name -> google.protobuf.Timestamp
	4, // 5: media.v1.ProjectObject.modified_at:type_name -> google.protobuf.Timestamp
	4, // 6: media.v1.ProjectCollection.created_at:type_name -> google.protobuf.Timestamp
	4, // 7: media.v1.ProjectCollection.last_modified:type_name -> google.protobuf.Timestamp
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_media_v1_assets_proto_init() }
func file_media_v1_assets_proto_init() {
	if File_media_v1_assets_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_v1_assets_proto_rawDesc), len(file_media_v1_assets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_media_v1_assets_proto_goTypes,
		DependencyIndexes: file_media_v1_assets_proto_depIdxs,
		MessageInfos:      file_media_v1_assets_proto_msgTypes,
	}.Build()
	File_media_v1_assets_proto = out.File
	file_media_v1_assets_proto_goTypes = nil
	file_media_v1_assets_proto_depIdxs = nil
}
