// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: media/v1/service.proto

package mediav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_media_v1_service_proto protoreflect.FileDescriptor

const file_media_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x16media/v1/service.proto\x12\bmedia.v1\x1a\x14media/v1/media.proto2i\n" +
	"\fMediaService\x12Y\n" +
	"\x10CreateNewProject\x12!.media.v1.CreateNewProjectRequest\x1a\".media.v1.CreateNewProjectResponseB7Z5github.com/lucas-woo/cloud-drive/api/media/v1/mediav1b\x06proto3"

var file_media_v1_service_proto_goTypes = []any{
	(*CreateNewProjectRequest)(nil),  // 0: media.v1.CreateNewProjectRequest
	(*CreateNewProjectResponse)(nil), // 1: media.v1.CreateNewProjectResponse
}
var file_media_v1_service_proto_depIdxs = []int32{
	0, // 0: media.v1.MediaService.CreateNewProject:input_type -> media.v1.CreateNewProjectRequest
	1, // 1: media.v1.MediaService.CreateNewProject:output_type -> media.v1.CreateNewProjectResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_media_v1_service_proto_init() }
func file_media_v1_service_proto_init() {
	if File_media_v1_service_proto != nil {
		return
	}
	file_media_v1_media_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_v1_service_proto_rawDesc), len(file_media_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_media_v1_service_proto_goTypes,
		DependencyIndexes: file_media_v1_service_proto_depIdxs,
	}.Build()
	File_media_v1_service_proto = out.File
	file_media_v1_service_proto_goTypes = nil
	file_media_v1_service_proto_depIdxs = nil
}
