// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: media/v1/service.proto

package mediav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_media_v1_service_proto protoreflect.FileDescriptor

const file_media_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x16media/v1/service.proto\x12\bmedia.v1\x1a\x14media/v1/media.proto2\xdc\x03\n" +
	"\fMediaService\x12Y\n" +
	"\x10CreateNewProject\x12!.media.v1.CreateNewProjectRequest\x1a\".media.v1.CreateNewProjectResponse\x12M\n" +
	"\fUploadObject\x12\x1d.media.v1.UploadObjectRequest\x1a\x1e.media.v1.UploadObjectResponse\x12U\n" +
	"\x0eUploadImageApi\x12\x1f.media.v1.UploadImageApiRequest\x1a .media.v1.UploadImageApiResponse(\x01\x12R\n" +
	"\rUploadFileApi\x12\x1e.media.v1.UploadFileApiRequest\x1a\x1f.media.v1.UploadFileApiResponse(\x01\x12w\n" +
	"\x1aLambdaS3UploadConfirmation\x12+.media.v1.LambdaS3UploadConfirmationRequest\x1a,.media.v1.LambdaS3UploadConfirmationResponseB7Z5github.com/lucas-woo/cloud-drive/api/media/v1/mediav1b\x06proto3"

var file_media_v1_service_proto_goTypes = []any{
	(*CreateNewProjectRequest)(nil),            // 0: media.v1.CreateNewProjectRequest
	(*UploadObjectRequest)(nil),                // 1: media.v1.UploadObjectRequest
	(*UploadImageApiRequest)(nil),              // 2: media.v1.UploadImageApiRequest
	(*UploadFileApiRequest)(nil),               // 3: media.v1.UploadFileApiRequest
	(*LambdaS3UploadConfirmationRequest)(nil),  // 4: media.v1.LambdaS3UploadConfirmationRequest
	(*CreateNewProjectResponse)(nil),           // 5: media.v1.CreateNewProjectResponse
	(*UploadObjectResponse)(nil),               // 6: media.v1.UploadObjectResponse
	(*UploadImageApiResponse)(nil),             // 7: media.v1.UploadImageApiResponse
	(*UploadFileApiResponse)(nil),              // 8: media.v1.UploadFileApiResponse
	(*LambdaS3UploadConfirmationResponse)(nil), // 9: media.v1.LambdaS3UploadConfirmationResponse
}
var file_media_v1_service_proto_depIdxs = []int32{
	0, // 0: media.v1.MediaService.CreateNewProject:input_type -> media.v1.CreateNewProjectRequest
	1, // 1: media.v1.MediaService.UploadObject:input_type -> media.v1.UploadObjectRequest
	2, // 2: media.v1.MediaService.UploadImageApi:input_type -> media.v1.UploadImageApiRequest
	3, // 3: media.v1.MediaService.UploadFileApi:input_type -> media.v1.UploadFileApiRequest
	4, // 4: media.v1.MediaService.LambdaS3UploadConfirmation:input_type -> media.v1.LambdaS3UploadConfirmationRequest
	5, // 5: media.v1.MediaService.CreateNewProject:output_type -> media.v1.CreateNewProjectResponse
	6, // 6: media.v1.MediaService.UploadObject:output_type -> media.v1.UploadObjectResponse
	7, // 7: media.v1.MediaService.UploadImageApi:output_type -> media.v1.UploadImageApiResponse
	8, // 8: media.v1.MediaService.UploadFileApi:output_type -> media.v1.UploadFileApiResponse
	9, // 9: media.v1.MediaService.LambdaS3UploadConfirmation:output_type -> media.v1.LambdaS3UploadConfirmationResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_media_v1_service_proto_init() }
func file_media_v1_service_proto_init() {
	if File_media_v1_service_proto != nil {
		return
	}
	file_media_v1_media_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_v1_service_proto_rawDesc), len(file_media_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_media_v1_service_proto_goTypes,
		DependencyIndexes: file_media_v1_service_proto_depIdxs,
	}.Build()
	File_media_v1_service_proto = out.File
	file_media_v1_service_proto_goTypes = nil
	file_media_v1_service_proto_depIdxs = nil
}
