// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: media/v1/service.proto

package mediav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MediaService_CreateNewProject_FullMethodName         = "/media.v1.MediaService/CreateNewProject"
	MediaService_UploadObject_FullMethodName             = "/media.v1.MediaService/UploadObject"
	MediaService_UploadImageApi_FullMethodName           = "/media.v1.MediaService/UploadImageApi"
	MediaService_UploadFileApi_FullMethodName            = "/media.v1.MediaService/UploadFileApi"
	MediaService_ObjectUploadConfirmation_FullMethodName = "/media.v1.MediaService/ObjectUploadConfirmation"
	MediaService_GetDashboard_FullMethodName             = "/media.v1.MediaService/GetDashboard"
	MediaService_GetAssets_FullMethodName                = "/media.v1.MediaService/GetAssets"
	MediaService_GetAllFolders_FullMethodName            = "/media.v1.MediaService/GetAllFolders"
)

// MediaServiceClient is the client API for MediaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MediaServiceClient interface {
	CreateNewProject(ctx context.Context, in *CreateNewProjectRequest, opts ...grpc.CallOption) (*CreateNewProjectResponse, error)
	UploadObject(ctx context.Context, in *UploadObjectRequest, opts ...grpc.CallOption) (*UploadObjectResponse, error)
	UploadImageApi(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadImageApiRequest, UploadImageApiResponse], error)
	UploadFileApi(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadFileApiRequest, UploadFileApiResponse], error)
	ObjectUploadConfirmation(ctx context.Context, in *ObjectUploadConfirmationRequest, opts ...grpc.CallOption) (*ObjectUploadConfirmationResponse, error)
	GetDashboard(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardResponse, error)
	GetAssets(ctx context.Context, in *GetAssetsRequest, opts ...grpc.CallOption) (*GetAssetsResponse, error)
	GetAllFolders(ctx context.Context, in *GetAllFoldersRequest, opts ...grpc.CallOption) (*GetAllFoldersResponse, error)
}

type mediaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMediaServiceClient(cc grpc.ClientConnInterface) MediaServiceClient {
	return &mediaServiceClient{cc}
}

func (c *mediaServiceClient) CreateNewProject(ctx context.Context, in *CreateNewProjectRequest, opts ...grpc.CallOption) (*CreateNewProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNewProjectResponse)
	err := c.cc.Invoke(ctx, MediaService_CreateNewProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) UploadObject(ctx context.Context, in *UploadObjectRequest, opts ...grpc.CallOption) (*UploadObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadObjectResponse)
	err := c.cc.Invoke(ctx, MediaService_UploadObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) UploadImageApi(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadImageApiRequest, UploadImageApiResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MediaService_ServiceDesc.Streams[0], MediaService_UploadImageApi_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadImageApiRequest, UploadImageApiResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MediaService_UploadImageApiClient = grpc.ClientStreamingClient[UploadImageApiRequest, UploadImageApiResponse]

func (c *mediaServiceClient) UploadFileApi(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadFileApiRequest, UploadFileApiResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MediaService_ServiceDesc.Streams[1], MediaService_UploadFileApi_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadFileApiRequest, UploadFileApiResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MediaService_UploadFileApiClient = grpc.ClientStreamingClient[UploadFileApiRequest, UploadFileApiResponse]

func (c *mediaServiceClient) ObjectUploadConfirmation(ctx context.Context, in *ObjectUploadConfirmationRequest, opts ...grpc.CallOption) (*ObjectUploadConfirmationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObjectUploadConfirmationResponse)
	err := c.cc.Invoke(ctx, MediaService_ObjectUploadConfirmation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) GetDashboard(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDashboardResponse)
	err := c.cc.Invoke(ctx, MediaService_GetDashboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) GetAssets(ctx context.Context, in *GetAssetsRequest, opts ...grpc.CallOption) (*GetAssetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAssetsResponse)
	err := c.cc.Invoke(ctx, MediaService_GetAssets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) GetAllFolders(ctx context.Context, in *GetAllFoldersRequest, opts ...grpc.CallOption) (*GetAllFoldersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllFoldersResponse)
	err := c.cc.Invoke(ctx, MediaService_GetAllFolders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MediaServiceServer is the server API for MediaService service.
// All implementations must embed UnimplementedMediaServiceServer
// for forward compatibility.
type MediaServiceServer interface {
	CreateNewProject(context.Context, *CreateNewProjectRequest) (*CreateNewProjectResponse, error)
	UploadObject(context.Context, *UploadObjectRequest) (*UploadObjectResponse, error)
	UploadImageApi(grpc.ClientStreamingServer[UploadImageApiRequest, UploadImageApiResponse]) error
	UploadFileApi(grpc.ClientStreamingServer[UploadFileApiRequest, UploadFileApiResponse]) error
	ObjectUploadConfirmation(context.Context, *ObjectUploadConfirmationRequest) (*ObjectUploadConfirmationResponse, error)
	GetDashboard(context.Context, *GetDashboardRequest) (*GetDashboardResponse, error)
	GetAssets(context.Context, *GetAssetsRequest) (*GetAssetsResponse, error)
	GetAllFolders(context.Context, *GetAllFoldersRequest) (*GetAllFoldersResponse, error)
	mustEmbedUnimplementedMediaServiceServer()
}

// UnimplementedMediaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMediaServiceServer struct{}

func (UnimplementedMediaServiceServer) CreateNewProject(context.Context, *CreateNewProjectRequest) (*CreateNewProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNewProject not implemented")
}
func (UnimplementedMediaServiceServer) UploadObject(context.Context, *UploadObjectRequest) (*UploadObjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadObject not implemented")
}
func (UnimplementedMediaServiceServer) UploadImageApi(grpc.ClientStreamingServer[UploadImageApiRequest, UploadImageApiResponse]) error {
	return status.Error(codes.Unimplemented, "method UploadImageApi not implemented")
}
func (UnimplementedMediaServiceServer) UploadFileApi(grpc.ClientStreamingServer[UploadFileApiRequest, UploadFileApiResponse]) error {
	return status.Error(codes.Unimplemented, "method UploadFileApi not implemented")
}
func (UnimplementedMediaServiceServer) ObjectUploadConfirmation(context.Context, *ObjectUploadConfirmationRequest) (*ObjectUploadConfirmationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ObjectUploadConfirmation not implemented")
}
func (UnimplementedMediaServiceServer) GetDashboard(context.Context, *GetDashboardRequest) (*GetDashboardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDashboard not implemented")
}
func (UnimplementedMediaServiceServer) GetAssets(context.Context, *GetAssetsRequest) (*GetAssetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAssets not implemented")
}
func (UnimplementedMediaServiceServer) GetAllFolders(context.Context, *GetAllFoldersRequest) (*GetAllFoldersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllFolders not implemented")
}
func (UnimplementedMediaServiceServer) mustEmbedUnimplementedMediaServiceServer() {}
func (UnimplementedMediaServiceServer) testEmbeddedByValue()                      {}

// UnsafeMediaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MediaServiceServer will
// result in compilation errors.
type UnsafeMediaServiceServer interface {
	mustEmbedUnimplementedMediaServiceServer()
}

func RegisterMediaServiceServer(s grpc.ServiceRegistrar, srv MediaServiceServer) {
	// If the following call panics, it indicates UnimplementedMediaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MediaService_ServiceDesc, srv)
}

func _MediaService_CreateNewProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNewProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).CreateNewProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_CreateNewProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).CreateNewProject(ctx, req.(*CreateNewProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_UploadObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).UploadObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_UploadObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).UploadObject(ctx, req.(*UploadObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_UploadImageApi_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MediaServiceServer).UploadImageApi(&grpc.GenericServerStream[UploadImageApiRequest, UploadImageApiResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MediaService_UploadImageApiServer = grpc.ClientStreamingServer[UploadImageApiRequest, UploadImageApiResponse]

func _MediaService_UploadFileApi_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MediaServiceServer).UploadFileApi(&grpc.GenericServerStream[UploadFileApiRequest, UploadFileApiResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MediaService_UploadFileApiServer = grpc.ClientStreamingServer[UploadFileApiRequest, UploadFileApiResponse]

func _MediaService_ObjectUploadConfirmation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectUploadConfirmationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).ObjectUploadConfirmation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_ObjectUploadConfirmation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).ObjectUploadConfirmation(ctx, req.(*ObjectUploadConfirmationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_GetDashboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).GetDashboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_GetDashboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).GetDashboard(ctx, req.(*GetDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_GetAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).GetAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_GetAssets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).GetAssets(ctx, req.(*GetAssetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_GetAllFolders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllFoldersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).GetAllFolders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_GetAllFolders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).GetAllFolders(ctx, req.(*GetAllFoldersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MediaService_ServiceDesc is the grpc.ServiceDesc for MediaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MediaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "media.v1.MediaService",
	HandlerType: (*MediaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNewProject",
			Handler:    _MediaService_CreateNewProject_Handler,
		},
		{
			MethodName: "UploadObject",
			Handler:    _MediaService_UploadObject_Handler,
		},
		{
			MethodName: "ObjectUploadConfirmation",
			Handler:    _MediaService_ObjectUploadConfirmation_Handler,
		},
		{
			MethodName: "GetDashboard",
			Handler:    _MediaService_GetDashboard_Handler,
		},
		{
			MethodName: "GetAssets",
			Handler:    _MediaService_GetAssets_Handler,
		},
		{
			MethodName: "GetAllFolders",
			Handler:    _MediaService_GetAllFolders_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadImageApi",
			Handler:       _MediaService_UploadImageApi_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "UploadFileApi",
			Handler:       _MediaService_UploadFileApi_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "media/v1/service.proto",
}
