// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: media/v1/transformations.proto

package mediav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Crop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         uint32                 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Crop) Reset() {
	*x = Crop{}
	mi := &file_media_v1_transformations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Crop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Crop) ProtoMessage() {}

func (x *Crop) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_transformations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Crop.ProtoReflect.Descriptor instead.
func (*Crop) Descriptor() ([]byte, []int) {
	return file_media_v1_transformations_proto_rawDescGZIP(), []int{0}
}

func (x *Crop) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Crop) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type Scale struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         uint32                 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scale) Reset() {
	*x = Scale{}
	mi := &file_media_v1_transformations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scale) ProtoMessage() {}

func (x *Scale) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_transformations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scale.ProtoReflect.Descriptor instead.
func (*Scale) Descriptor() ([]byte, []int) {
	return file_media_v1_transformations_proto_rawDescGZIP(), []int{1}
}

func (x *Scale) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Scale) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type Compression struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Compress      bool                   `protobuf:"varint,1,opt,name=compress,proto3" json:"compress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Compression) Reset() {
	*x = Compression{}
	mi := &file_media_v1_transformations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Compression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Compression) ProtoMessage() {}

func (x *Compression) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_transformations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Compression.ProtoReflect.Descriptor instead.
func (*Compression) Descriptor() ([]byte, []int) {
	return file_media_v1_transformations_proto_rawDescGZIP(), []int{2}
}

func (x *Compression) GetCompress() bool {
	if x != nil {
		return x.Compress
	}
	return false
}

type Conversion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        string                 `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conversion) Reset() {
	*x = Conversion{}
	mi := &file_media_v1_transformations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversion) ProtoMessage() {}

func (x *Conversion) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_transformations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversion.ProtoReflect.Descriptor instead.
func (*Conversion) Descriptor() ([]byte, []int) {
	return file_media_v1_transformations_proto_rawDescGZIP(), []int{3}
}

func (x *Conversion) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

var File_media_v1_transformations_proto protoreflect.FileDescriptor

const file_media_v1_transformations_proto_rawDesc = "" +
	"\n" +
	"\x1emedia/v1/transformations.proto\x12\bmedia.v1\"4\n" +
	"\x04Crop\x12\x14\n" +
	"\x05width\x18\x01 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\rR\x06height\"5\n" +
	"\x05Scale\x12\x14\n" +
	"\x05width\x18\x01 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\rR\x06height\")\n" +
	"\vCompression\x12\x1a\n" +
	"\bcompress\x18\x01 \x01(\bR\bcompress\"$\n" +
	"\n" +
	"Conversion\x12\x16\n" +
	"\x06format\x18\x01 \x01(\tR\x06formatB7Z5github.com/lucas-woo/cloud-drive/api/media/v1/mediav1b\x06proto3"

var (
	file_media_v1_transformations_proto_rawDescOnce sync.Once
	file_media_v1_transformations_proto_rawDescData []byte
)

func file_media_v1_transformations_proto_rawDescGZIP() []byte {
	file_media_v1_transformations_proto_rawDescOnce.Do(func() {
		file_media_v1_transformations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_v1_transformations_proto_rawDesc), len(file_media_v1_transformations_proto_rawDesc)))
	})
	return file_media_v1_transformations_proto_rawDescData
}

var file_media_v1_transformations_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_media_v1_transformations_proto_goTypes = []any{
	(*Crop)(nil),        // 0: media.v1.Crop
	(*Scale)(nil),       // 1: media.v1.Scale
	(*Compression)(nil), // 2: media.v1.Compression
	(*Conversion)(nil),  // 3: media.v1.Conversion
}
var file_media_v1_transformations_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_media_v1_transformations_proto_init() }
func file_media_v1_transformations_proto_init() {
	if File_media_v1_transformations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_v1_transformations_proto_rawDesc), len(file_media_v1_transformations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_media_v1_transformations_proto_goTypes,
		DependencyIndexes: file_media_v1_transformations_proto_depIdxs,
		MessageInfos:      file_media_v1_transformations_proto_msgTypes,
	}.Build()
	File_media_v1_transformations_proto = out.File
	file_media_v1_transformations_proto_goTypes = nil
	file_media_v1_transformations_proto_depIdxs = nil
}
