// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: auth/v1/service.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_auth_v1_service_proto protoreflect.FileDescriptor

const file_auth_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x15auth/v1/service.proto\x12\aauth.v1\x1a\x12auth/v1/auth.proto2\xc1\x02\n" +
	"\vAuthService\x12E\n" +
	"\n" +
	"SignUpUser\x12\x1a.auth.v1.SignUpUserRequest\x1a\x1b.auth.v1.SignUpUserResponse\x12B\n" +
	"\tLoginUser\x12\x19.auth.v1.LoginUserRequest\x1a\x1a.auth.v1.LoginUserResponse\x12E\n" +
	"\n" +
	"LogoutUser\x12\x1a.auth.v1.LogoutUserRequest\x1a\x1b.auth.v1.LogoutUserResponse\x12`\n" +
	"\x13ValidateUserSession\x12#.auth.v1.ValidateUserSessionRequest\x1a$.auth.v1.ValidateUserSessionResponseB5Z3github.com/lucas-woo/cloud-drive/api/auth/v1/authv1b\x06proto3"

var file_auth_v1_service_proto_goTypes = []any{
	(*SignUpUserRequest)(nil),           // 0: auth.v1.SignUpUserRequest
	(*LoginUserRequest)(nil),            // 1: auth.v1.LoginUserRequest
	(*LogoutUserRequest)(nil),           // 2: auth.v1.LogoutUserRequest
	(*ValidateUserSessionRequest)(nil),  // 3: auth.v1.ValidateUserSessionRequest
	(*SignUpUserResponse)(nil),          // 4: auth.v1.SignUpUserResponse
	(*LoginUserResponse)(nil),           // 5: auth.v1.LoginUserResponse
	(*LogoutUserResponse)(nil),          // 6: auth.v1.LogoutUserResponse
	(*ValidateUserSessionResponse)(nil), // 7: auth.v1.ValidateUserSessionResponse
}
var file_auth_v1_service_proto_depIdxs = []int32{
	0, // 0: auth.v1.AuthService.SignUpUser:input_type -> auth.v1.SignUpUserRequest
	1, // 1: auth.v1.AuthService.LoginUser:input_type -> auth.v1.LoginUserRequest
	2, // 2: auth.v1.AuthService.LogoutUser:input_type -> auth.v1.LogoutUserRequest
	3, // 3: auth.v1.AuthService.ValidateUserSession:input_type -> auth.v1.ValidateUserSessionRequest
	4, // 4: auth.v1.AuthService.SignUpUser:output_type -> auth.v1.SignUpUserResponse
	5, // 5: auth.v1.AuthService.LoginUser:output_type -> auth.v1.LoginUserResponse
	6, // 6: auth.v1.AuthService.LogoutUser:output_type -> auth.v1.LogoutUserResponse
	7, // 7: auth.v1.AuthService.ValidateUserSession:output_type -> auth.v1.ValidateUserSessionResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_v1_service_proto_init() }
func file_auth_v1_service_proto_init() {
	if File_auth_v1_service_proto != nil {
		return
	}
	file_auth_v1_auth_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_service_proto_rawDesc), len(file_auth_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_service_proto_goTypes,
		DependencyIndexes: file_auth_v1_service_proto_depIdxs,
	}.Build()
	File_auth_v1_service_proto = out.File
	file_auth_v1_service_proto_goTypes = nil
	file_auth_v1_service_proto_depIdxs = nil
}
