// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: iam/v1/iam.proto

package iamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateApiKeyPermissionRequest_Permission int32

const (
	ValidateApiKeyPermissionRequest_PERMISSION_STATUS_UNSPECIFIED ValidateApiKeyPermissionRequest_Permission = 0
	ValidateApiKeyPermissionRequest_PERMISSION_CREATE             ValidateApiKeyPermissionRequest_Permission = 1
	ValidateApiKeyPermissionRequest_PERMISSION_DELETE             ValidateApiKeyPermissionRequest_Permission = 2
)

// Enum value maps for ValidateApiKeyPermissionRequest_Permission.
var (
	ValidateApiKeyPermissionRequest_Permission_name = map[int32]string{
		0: "PERMISSION_STATUS_UNSPECIFIED",
		1: "PERMISSION_CREATE",
		2: "PERMISSION_DELETE",
	}
	ValidateApiKeyPermissionRequest_Permission_value = map[string]int32{
		"PERMISSION_STATUS_UNSPECIFIED": 0,
		"PERMISSION_CREATE":             1,
		"PERMISSION_DELETE":             2,
	}
)

func (x ValidateApiKeyPermissionRequest_Permission) Enum() *ValidateApiKeyPermissionRequest_Permission {
	p := new(ValidateApiKeyPermissionRequest_Permission)
	*p = x
	return p
}

func (x ValidateApiKeyPermissionRequest_Permission) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidateApiKeyPermissionRequest_Permission) Descriptor() protoreflect.EnumDescriptor {
	return file_iam_v1_iam_proto_enumTypes[0].Descriptor()
}

func (ValidateApiKeyPermissionRequest_Permission) Type() protoreflect.EnumType {
	return &file_iam_v1_iam_proto_enumTypes[0]
}

func (x ValidateApiKeyPermissionRequest_Permission) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidateApiKeyPermissionRequest_Permission.Descriptor instead.
func (ValidateApiKeyPermissionRequest_Permission) EnumDescriptor() ([]byte, []int) {
	return file_iam_v1_iam_proto_rawDescGZIP(), []int{2, 0}
}

type AddUserRolePermissionRequest_Permission int32

const (
	AddUserRolePermissionRequest_PERMISSION_STATUS_UNSPECIFIED AddUserRolePermissionRequest_Permission = 0
	AddUserRolePermissionRequest_PERMISSION_ADMIN_ROLE         AddUserRolePermissionRequest_Permission = 1
)

// Enum value maps for AddUserRolePermissionRequest_Permission.
var (
	AddUserRolePermissionRequest_Permission_name = map[int32]string{
		0: "PERMISSION_STATUS_UNSPECIFIED",
		1: "PERMISSION_ADMIN_ROLE",
	}
	AddUserRolePermissionRequest_Permission_value = map[string]int32{
		"PERMISSION_STATUS_UNSPECIFIED": 0,
		"PERMISSION_ADMIN_ROLE":         1,
	}
)

func (x AddUserRolePermissionRequest_Permission) Enum() *AddUserRolePermissionRequest_Permission {
	p := new(AddUserRolePermissionRequest_Permission)
	*p = x
	return p
}

func (x AddUserRolePermissionRequest_Permission) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AddUserRolePermissionRequest_Permission) Descriptor() protoreflect.EnumDescriptor {
	return file_iam_v1_iam_proto_enumTypes[1].Descriptor()
}

func (AddUserRolePermissionRequest_Permission) Type() protoreflect.EnumType {
	return &file_iam_v1_iam_proto_enumTypes[1]
}

func (x AddUserRolePermissionRequest_Permission) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AddUserRolePermissionRequest_Permission.Descriptor instead.
func (AddUserRolePermissionRequest_Permission) EnumDescriptor() ([]byte, []int) {
	return file_iam_v1_iam_proto_rawDescGZIP(), []int{4, 0}
}

type ValidateUserPermissionRequest_Permission int32

const (
	ValidateUserPermissionRequest_PERMISSION_STATUS_UNSPECIFIED ValidateUserPermissionRequest_Permission = 0
	ValidateUserPermissionRequest_PERMISSION_ADMIN_ROLE         ValidateUserPermissionRequest_Permission = 1
)

// Enum value maps for ValidateUserPermissionRequest_Permission.
var (
	ValidateUserPermissionRequest_Permission_name = map[int32]string{
		0: "PERMISSION_STATUS_UNSPECIFIED",
		1: "PERMISSION_ADMIN_ROLE",
	}
	ValidateUserPermissionRequest_Permission_value = map[string]int32{
		"PERMISSION_STATUS_UNSPECIFIED": 0,
		"PERMISSION_ADMIN_ROLE":         1,
	}
)

func (x ValidateUserPermissionRequest_Permission) Enum() *ValidateUserPermissionRequest_Permission {
	p := new(ValidateUserPermissionRequest_Permission)
	*p = x
	return p
}

func (x ValidateUserPermissionRequest_Permission) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidateUserPermissionRequest_Permission) Descriptor() protoreflect.EnumDescriptor {
	return file_iam_v1_iam_proto_enumTypes[2].Descriptor()
}

func (ValidateUserPermissionRequest_Permission) Type() protoreflect.EnumType {
	return &file_iam_v1_iam_proto_enumTypes[2]
}

func (x ValidateUserPermissionRequest_Permission) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidateUserPermissionRequest_Permission.Descriptor instead.
func (ValidateUserPermissionRequest_Permission) EnumDescriptor() ([]byte, []int) {
	return file_iam_v1_iam_proto_rawDescGZIP(), []int{6, 0}
}

type GenerateNewApiKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	KeyName       string                 `protobuf:"bytes,2,opt,name=key_name,json=keyName,proto3" json:"key_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateNewApiKeyRequest) Reset() {
	*x = GenerateNewApiKeyRequest{}
	mi := &file_iam_v1_iam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateNewApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateNewApiKeyRequest) ProtoMessage() {}

func (x *GenerateNewApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_iam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateNewApiKeyRequest.ProtoReflect.Descriptor instead.
func (*GenerateNewApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_iam_v1_iam_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateNewApiKeyRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GenerateNewApiKeyRequest) GetKeyName() string {
	if x != nil {
		return x.KeyName
	}
	return ""
}

type GenerateNewApiKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	ApiSecret     string                 `protobuf:"bytes,2,opt,name=api_secret,json=apiSecret,proto3" json:"api_secret,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateNewApiKeyResponse) Reset() {
	*x = GenerateNewApiKeyResponse{}
	mi := &file_iam_v1_iam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateNewApiKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateNewApiKeyResponse) ProtoMessage() {}

func (x *GenerateNewApiKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_iam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateNewApiKeyResponse.ProtoReflect.Descriptor instead.
func (*GenerateNewApiKeyResponse) Descriptor() ([]byte, []int) {
	return file_iam_v1_iam_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateNewApiKeyResponse) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *GenerateNewApiKeyResponse) GetApiSecret() string {
	if x != nil {
		return x.ApiSecret
	}
	return ""
}

func (x *GenerateNewApiKeyResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ValidateApiKeyPermissionRequest struct {
	state         protoimpl.MessageState                     `protogen:"open.v1"`
	ApiKey        string                                     `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	ApiSecret     string                                     `protobuf:"bytes,2,opt,name=api_secret,json=apiSecret,proto3" json:"api_secret,omitempty"`
	Permission    ValidateApiKeyPermissionRequest_Permission `protobuf:"varint,3,opt,name=permission,proto3,enum=iam.v1.ValidateApiKeyPermissionRequest_Permission" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateApiKeyPermissionRequest) Reset() {
	*x = ValidateApiKeyPermissionRequest{}
	mi := &file_iam_v1_iam_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateApiKeyPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateApiKeyPermissionRequest) ProtoMessage() {}

func (x *ValidateApiKeyPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_iam_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateApiKeyPermissionRequest.ProtoReflect.Descriptor instead.
func (*ValidateApiKeyPermissionRequest) Descriptor() ([]byte, []int) {
	return file_iam_v1_iam_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateApiKeyPermissionRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *ValidateApiKeyPermissionRequest) GetApiSecret() string {
	if x != nil {
		return x.ApiSecret
	}
	return ""
}

func (x *ValidateApiKeyPermissionRequest) GetPermission() ValidateApiKeyPermissionRequest_Permission {
	if x != nil {
		return x.Permission
	}
	return ValidateApiKeyPermissionRequest_PERMISSION_STATUS_UNSPECIFIED
}

type ValidateApiKeyPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authorized    bool                   `protobuf:"varint,1,opt,name=authorized,proto3" json:"authorized,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateApiKeyPermissionResponse) Reset() {
	*x = ValidateApiKeyPermissionResponse{}
	mi := &file_iam_v1_iam_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateApiKeyPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateApiKeyPermissionResponse) ProtoMessage() {}

func (x *ValidateApiKeyPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_iam_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateApiKeyPermissionResponse.ProtoReflect.Descriptor instead.
func (*ValidateApiKeyPermissionResponse) Descriptor() ([]byte, []int) {
	return file_iam_v1_iam_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateApiKeyPermissionResponse) GetAuthorized() bool {
	if x != nil {
		return x.Authorized
	}
	return false
}

type AddUserRolePermissionRequest struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	UserId        string                                  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProjectId     string                                  `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Role          AddUserRolePermissionRequest_Permission `protobuf:"varint,3,opt,name=role,proto3,enum=iam.v1.AddUserRolePermissionRequest_Permission" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserRolePermissionRequest) Reset() {
	*x = AddUserRolePermissionRequest{}
	mi := &file_iam_v1_iam_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserRolePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserRolePermissionRequest) ProtoMessage() {}

func (x *AddUserRolePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_iam_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserRolePermissionRequest.ProtoReflect.Descriptor instead.
func (*AddUserRolePermissionRequest) Descriptor() ([]byte, []int) {
	return file_iam_v1_iam_proto_rawDescGZIP(), []int{4}
}

func (x *AddUserRolePermissionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddUserRolePermissionRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *AddUserRolePermissionRequest) GetRole() AddUserRolePermissionRequest_Permission {
	if x != nil {
		return x.Role
	}
	return AddUserRolePermissionRequest_PERMISSION_STATUS_UNSPECIFIED
}

type AddUserRolePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updated       bool                   `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserRolePermissionResponse) Reset() {
	*x = AddUserRolePermissionResponse{}
	mi := &file_iam_v1_iam_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserRolePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserRolePermissionResponse) ProtoMessage() {}

func (x *AddUserRolePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_iam_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserRolePermissionResponse.ProtoReflect.Descriptor instead.
func (*AddUserRolePermissionResponse) Descriptor() ([]byte, []int) {
	return file_iam_v1_iam_proto_rawDescGZIP(), []int{5}
}

func (x *AddUserRolePermissionResponse) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

type ValidateUserPermissionRequest struct {
	state         protoimpl.MessageState                   `protogen:"open.v1"`
	UserId        string                                   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProjectId     string                                   `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Role          ValidateUserPermissionRequest_Permission `protobuf:"varint,3,opt,name=role,proto3,enum=iam.v1.ValidateUserPermissionRequest_Permission" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateUserPermissionRequest) Reset() {
	*x = ValidateUserPermissionRequest{}
	mi := &file_iam_v1_iam_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateUserPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateUserPermissionRequest) ProtoMessage() {}

func (x *ValidateUserPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_iam_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateUserPermissionRequest.ProtoReflect.Descriptor instead.
func (*ValidateUserPermissionRequest) Descriptor() ([]byte, []int) {
	return file_iam_v1_iam_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateUserPermissionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateUserPermissionRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ValidateUserPermissionRequest) GetRole() ValidateUserPermissionRequest_Permission {
	if x != nil {
		return x.Role
	}
	return ValidateUserPermissionRequest_PERMISSION_STATUS_UNSPECIFIED
}

type ValidateUserPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authorized    bool                   `protobuf:"varint,1,opt,name=authorized,proto3" json:"authorized,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateUserPermissionResponse) Reset() {
	*x = ValidateUserPermissionResponse{}
	mi := &file_iam_v1_iam_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateUserPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateUserPermissionResponse) ProtoMessage() {}

func (x *ValidateUserPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_iam_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateUserPermissionResponse.ProtoReflect.Descriptor instead.
func (*ValidateUserPermissionResponse) Descriptor() ([]byte, []int) {
	return file_iam_v1_iam_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateUserPermissionResponse) GetAuthorized() bool {
	if x != nil {
		return x.Authorized
	}
	return false
}

type ApiKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	KeyName       string                 `protobuf:"bytes,2,opt,name=key_name,json=keyName,proto3" json:"key_name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKey) Reset() {
	*x = ApiKey{}
	mi := &file_iam_v1_iam_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKey) ProtoMessage() {}

func (x *ApiKey) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_iam_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKey.ProtoReflect.Descriptor instead.
func (*ApiKey) Descriptor() ([]byte, []int) {
	return file_iam_v1_iam_proto_rawDescGZIP(), []int{8}
}

func (x *ApiKey) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *ApiKey) GetKeyName() string {
	if x != nil {
		return x.KeyName
	}
	return ""
}

func (x *ApiKey) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ApiKey) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type GetAllApiKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllApiKeysRequest) Reset() {
	*x = GetAllApiKeysRequest{}
	mi := &file_iam_v1_iam_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllApiKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllApiKeysRequest) ProtoMessage() {}

func (x *GetAllApiKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_iam_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllApiKeysRequest.ProtoReflect.Descriptor instead.
func (*GetAllApiKeysRequest) Descriptor() ([]byte, []int) {
	return file_iam_v1_iam_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllApiKeysRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type GetAllApiKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKeys       []*ApiKey              `protobuf:"bytes,1,rep,name=api_keys,json=apiKeys,proto3" json:"api_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllApiKeysResponse) Reset() {
	*x = GetAllApiKeysResponse{}
	mi := &file_iam_v1_iam_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllApiKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllApiKeysResponse) ProtoMessage() {}

func (x *GetAllApiKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_iam_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllApiKeysResponse.ProtoReflect.Descriptor instead.
func (*GetAllApiKeysResponse) Descriptor() ([]byte, []int) {
	return file_iam_v1_iam_proto_rawDescGZIP(), []int{10}
}

func (x *GetAllApiKeysResponse) GetApiKeys() []*ApiKey {
	if x != nil {
		return x.ApiKeys
	}
	return nil
}

type GetProjectIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	ApiSecret     string                 `protobuf:"bytes,2,opt,name=api_secret,json=apiSecret,proto3" json:"api_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectIdRequest) Reset() {
	*x = GetProjectIdRequest{}
	mi := &file_iam_v1_iam_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectIdRequest) ProtoMessage() {}

func (x *GetProjectIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_iam_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectIdRequest.ProtoReflect.Descriptor instead.
func (*GetProjectIdRequest) Descriptor() ([]byte, []int) {
	return file_iam_v1_iam_proto_rawDescGZIP(), []int{11}
}

func (x *GetProjectIdRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *GetProjectIdRequest) GetApiSecret() string {
	if x != nil {
		return x.ApiSecret
	}
	return ""
}

type GetProjectIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectIdResponse) Reset() {
	*x = GetProjectIdResponse{}
	mi := &file_iam_v1_iam_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectIdResponse) ProtoMessage() {}

func (x *GetProjectIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_iam_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectIdResponse.ProtoReflect.Descriptor instead.
func (*GetProjectIdResponse) Descriptor() ([]byte, []int) {
	return file_iam_v1_iam_proto_rawDescGZIP(), []int{12}
}

func (x *GetProjectIdResponse) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

var File_iam_v1_iam_proto protoreflect.FileDescriptor

const file_iam_v1_iam_proto_rawDesc = "" +
	"\n" +
	"\x10iam/v1/iam.proto\x12\x06iam.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"T\n" +
	"\x18GenerateNewApiKeyRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x19\n" +
	"\bkey_name\x18\x02 \x01(\tR\akeyName\"\x8e\x01\n" +
	"\x19GenerateNewApiKeyResponse\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x1d\n" +
	"\n" +
	"api_secret\x18\x02 \x01(\tR\tapiSecret\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x8c\x02\n" +
	"\x1fValidateApiKeyPermissionRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x1d\n" +
	"\n" +
	"api_secret\x18\x02 \x01(\tR\tapiSecret\x12R\n" +
	"\n" +
	"permission\x18\x03 \x01(\x0e22.iam.v1.ValidateApiKeyPermissionRequest.PermissionR\n" +
	"permission\"]\n" +
	"\n" +
	"Permission\x12!\n" +
	"\x1dPERMISSION_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11PERMISSION_CREATE\x10\x01\x12\x15\n" +
	"\x11PERMISSION_DELETE\x10\x02\"B\n" +
	" ValidateApiKeyPermissionResponse\x12\x1e\n" +
	"\n" +
	"authorized\x18\x01 \x01(\bR\n" +
	"authorized\"\xe7\x01\n" +
	"\x1cAddUserRolePermissionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12C\n" +
	"\x04role\x18\x03 \x01(\x0e2/.iam.v1.AddUserRolePermissionRequest.PermissionR\x04role\"J\n" +
	"\n" +
	"Permission\x12!\n" +
	"\x1dPERMISSION_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PERMISSION_ADMIN_ROLE\x10\x01\"9\n" +
	"\x1dAddUserRolePermissionResponse\x12\x18\n" +
	"\aupdated\x18\x01 \x01(\bR\aupdated\"\xe9\x01\n" +
	"\x1dValidateUserPermissionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12D\n" +
	"\x04role\x18\x03 \x01(\x0e20.iam.v1.ValidateUserPermissionRequest.PermissionR\x04role\"J\n" +
	"\n" +
	"Permission\x12!\n" +
	"\x1dPERMISSION_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PERMISSION_ADMIN_ROLE\x10\x01\"@\n" +
	"\x1eValidateUserPermissionResponse\x12\x1e\n" +
	"\n" +
	"authorized\x18\x01 \x01(\bR\n" +
	"authorized\"\x94\x01\n" +
	"\x06ApiKey\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x19\n" +
	"\bkey_name\x18\x02 \x01(\tR\akeyName\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\"5\n" +
	"\x14GetAllApiKeysRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"B\n" +
	"\x15GetAllApiKeysResponse\x12)\n" +
	"\bapi_keys\x18\x01 \x03(\v2\x0e.iam.v1.ApiKeyR\aapiKeys\"M\n" +
	"\x13GetProjectIdRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x1d\n" +
	"\n" +
	"api_secret\x18\x02 \x01(\tR\tapiSecret\"5\n" +
	"\x14GetProjectIdResponse\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectIdB3Z1github.com/lucas-woo/cloud-drive/api/iam/v1/iamv1b\x06proto3"

var (
	file_iam_v1_iam_proto_rawDescOnce sync.Once
	file_iam_v1_iam_proto_rawDescData []byte
)

func file_iam_v1_iam_proto_rawDescGZIP() []byte {
	file_iam_v1_iam_proto_rawDescOnce.Do(func() {
		file_iam_v1_iam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iam_v1_iam_proto_rawDesc), len(file_iam_v1_iam_proto_rawDesc)))
	})
	return file_iam_v1_iam_proto_rawDescData
}

var file_iam_v1_iam_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_iam_v1_iam_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_iam_v1_iam_proto_goTypes = []any{
	(ValidateApiKeyPermissionRequest_Permission)(0), // 0: iam.v1.ValidateApiKeyPermissionRequest.Permission
	(AddUserRolePermissionRequest_Permission)(0),    // 1: iam.v1.AddUserRolePermissionRequest.Permission
	(ValidateUserPermissionRequest_Permission)(0),   // 2: iam.v1.ValidateUserPermissionRequest.Permission
	(*GenerateNewApiKeyRequest)(nil),                // 3: iam.v1.GenerateNewApiKeyRequest
	(*GenerateNewApiKeyResponse)(nil),               // 4: iam.v1.GenerateNewApiKeyResponse
	(*ValidateApiKeyPermissionRequest)(nil),         // 5: iam.v1.ValidateApiKeyPermissionRequest
	(*ValidateApiKeyPermissionResponse)(nil),        // 6: iam.v1.ValidateApiKeyPermissionResponse
	(*AddUserRolePermissionRequest)(nil),            // 7: iam.v1.AddUserRolePermissionRequest
	(*AddUserRolePermissionResponse)(nil),           // 8: iam.v1.AddUserRolePermissionResponse
	(*ValidateUserPermissionRequest)(nil),           // 9: iam.v1.ValidateUserPermissionRequest
	(*ValidateUserPermissionResponse)(nil),          // 10: iam.v1.ValidateUserPermissionResponse
	(*ApiKey)(nil),                                  // 11: iam.v1.ApiKey
	(*GetAllApiKeysRequest)(nil),                    // 12: iam.v1.GetAllApiKeysRequest
	(*GetAllApiKeysResponse)(nil),                   // 13: iam.v1.GetAllApiKeysResponse
	(*GetProjectIdRequest)(nil),                     // 14: iam.v1.GetProjectIdRequest
	(*GetProjectIdResponse)(nil),                    // 15: iam.v1.GetProjectIdResponse
	(*timestamppb.Timestamp)(nil),                   // 16: google.protobuf.Timestamp
}
var file_iam_v1_iam_proto_depIdxs = []int32{
	16, // 0: iam.v1.GenerateNewApiKeyResponse.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: iam.v1.ValidateApiKeyPermissionRequest.permission:type_name -> iam.v1.ValidateApiKeyPermissionRequest.Permission
	1,  // 2: iam.v1.AddUserRolePermissionRequest.role:type_name -> iam.v1.AddUserRolePermissionRequest.Permission
	2,  // 3: iam.v1.ValidateUserPermissionRequest.role:type_name -> iam.v1.ValidateUserPermissionRequest.Permission
	16, // 4: iam.v1.ApiKey.created_at:type_name -> google.protobuf.Timestamp
	11, // 5: iam.v1.GetAllApiKeysResponse.api_keys:type_name -> iam.v1.ApiKey
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_iam_v1_iam_proto_init() }
func file_iam_v1_iam_proto_init() {
	if File_iam_v1_iam_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iam_v1_iam_proto_rawDesc), len(file_iam_v1_iam_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_iam_v1_iam_proto_goTypes,
		DependencyIndexes: file_iam_v1_iam_proto_depIdxs,
		EnumInfos:         file_iam_v1_iam_proto_enumTypes,
		MessageInfos:      file_iam_v1_iam_proto_msgTypes,
	}.Build()
	File_iam_v1_iam_proto = out.File
	file_iam_v1_iam_proto_goTypes = nil
	file_iam_v1_iam_proto_depIdxs = nil
}
