// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: iam/v1/iam.proto

package iamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateApiKeyPermissionRequest_Permission int32

const (
	ValidateApiKeyPermissionRequest_PERMISSION_STATUS_UNSPECIFIED ValidateApiKeyPermissionRequest_Permission = 0
	ValidateApiKeyPermissionRequest_PERMISSION_CREATE             ValidateApiKeyPermissionRequest_Permission = 1
	ValidateApiKeyPermissionRequest_PERMISSION_DELETE             ValidateApiKeyPermissionRequest_Permission = 2
)

// Enum value maps for ValidateApiKeyPermissionRequest_Permission.
var (
	ValidateApiKeyPermissionRequest_Permission_name = map[int32]string{
		0: "PERMISSION_STATUS_UNSPECIFIED",
		1: "PERMISSION_CREATE",
		2: "PERMISSION_DELETE",
	}
	ValidateApiKeyPermissionRequest_Permission_value = map[string]int32{
		"PERMISSION_STATUS_UNSPECIFIED": 0,
		"PERMISSION_CREATE":             1,
		"PERMISSION_DELETE":             2,
	}
)

func (x ValidateApiKeyPermissionRequest_Permission) Enum() *ValidateApiKeyPermissionRequest_Permission {
	p := new(ValidateApiKeyPermissionRequest_Permission)
	*p = x
	return p
}

func (x ValidateApiKeyPermissionRequest_Permission) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidateApiKeyPermissionRequest_Permission) Descriptor() protoreflect.EnumDescriptor {
	return file_iam_v1_iam_proto_enumTypes[0].Descriptor()
}

func (ValidateApiKeyPermissionRequest_Permission) Type() protoreflect.EnumType {
	return &file_iam_v1_iam_proto_enumTypes[0]
}

func (x ValidateApiKeyPermissionRequest_Permission) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidateApiKeyPermissionRequest_Permission.Descriptor instead.
func (ValidateApiKeyPermissionRequest_Permission) EnumDescriptor() ([]byte, []int) {
	return file_iam_v1_iam_proto_rawDescGZIP(), []int{2, 0}
}

type AddUserRoleRequest_Permission int32

const (
	AddUserRoleRequest_PERMISSION_STATUS_UNSPECIFIED AddUserRoleRequest_Permission = 0
	AddUserRoleRequest_PERMISSION_ADMIN_ROLE         AddUserRoleRequest_Permission = 1
)

// Enum value maps for AddUserRoleRequest_Permission.
var (
	AddUserRoleRequest_Permission_name = map[int32]string{
		0: "PERMISSION_STATUS_UNSPECIFIED",
		1: "PERMISSION_ADMIN_ROLE",
	}
	AddUserRoleRequest_Permission_value = map[string]int32{
		"PERMISSION_STATUS_UNSPECIFIED": 0,
		"PERMISSION_ADMIN_ROLE":         1,
	}
)

func (x AddUserRoleRequest_Permission) Enum() *AddUserRoleRequest_Permission {
	p := new(AddUserRoleRequest_Permission)
	*p = x
	return p
}

func (x AddUserRoleRequest_Permission) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AddUserRoleRequest_Permission) Descriptor() protoreflect.EnumDescriptor {
	return file_iam_v1_iam_proto_enumTypes[1].Descriptor()
}

func (AddUserRoleRequest_Permission) Type() protoreflect.EnumType {
	return &file_iam_v1_iam_proto_enumTypes[1]
}

func (x AddUserRoleRequest_Permission) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AddUserRoleRequest_Permission.Descriptor instead.
func (AddUserRoleRequest_Permission) EnumDescriptor() ([]byte, []int) {
	return file_iam_v1_iam_proto_rawDescGZIP(), []int{4, 0}
}

type ValidateUserPermissionRequest_Permission int32

const (
	ValidateUserPermissionRequest_PERMISSION_STATUS_UNSPECIFIED ValidateUserPermissionRequest_Permission = 0
	ValidateUserPermissionRequest_PERMISSION_ADMIN_ROLE         ValidateUserPermissionRequest_Permission = 1
)

// Enum value maps for ValidateUserPermissionRequest_Permission.
var (
	ValidateUserPermissionRequest_Permission_name = map[int32]string{
		0: "PERMISSION_STATUS_UNSPECIFIED",
		1: "PERMISSION_ADMIN_ROLE",
	}
	ValidateUserPermissionRequest_Permission_value = map[string]int32{
		"PERMISSION_STATUS_UNSPECIFIED": 0,
		"PERMISSION_ADMIN_ROLE":         1,
	}
)

func (x ValidateUserPermissionRequest_Permission) Enum() *ValidateUserPermissionRequest_Permission {
	p := new(ValidateUserPermissionRequest_Permission)
	*p = x
	return p
}

func (x ValidateUserPermissionRequest_Permission) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidateUserPermissionRequest_Permission) Descriptor() protoreflect.EnumDescriptor {
	return file_iam_v1_iam_proto_enumTypes[2].Descriptor()
}

func (ValidateUserPermissionRequest_Permission) Type() protoreflect.EnumType {
	return &file_iam_v1_iam_proto_enumTypes[2]
}

func (x ValidateUserPermissionRequest_Permission) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidateUserPermissionRequest_Permission.Descriptor instead.
func (ValidateUserPermissionRequest_Permission) EnumDescriptor() ([]byte, []int) {
	return file_iam_v1_iam_proto_rawDescGZIP(), []int{6, 0}
}

type GenerateNewApiKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	KeyName       string                 `protobuf:"bytes,3,opt,name=key_name,json=keyName,proto3" json:"key_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateNewApiKeyRequest) Reset() {
	*x = GenerateNewApiKeyRequest{}
	mi := &file_iam_v1_iam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateNewApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateNewApiKeyRequest) ProtoMessage() {}

func (x *GenerateNewApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_iam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateNewApiKeyRequest.ProtoReflect.Descriptor instead.
func (*GenerateNewApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_iam_v1_iam_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateNewApiKeyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GenerateNewApiKeyRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GenerateNewApiKeyRequest) GetKeyName() string {
	if x != nil {
		return x.KeyName
	}
	return ""
}

type GenerateNewApiKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	ApiSecret     string                 `protobuf:"bytes,2,opt,name=api_secret,json=apiSecret,proto3" json:"api_secret,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateNewApiKeyResponse) Reset() {
	*x = GenerateNewApiKeyResponse{}
	mi := &file_iam_v1_iam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateNewApiKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateNewApiKeyResponse) ProtoMessage() {}

func (x *GenerateNewApiKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_iam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateNewApiKeyResponse.ProtoReflect.Descriptor instead.
func (*GenerateNewApiKeyResponse) Descriptor() ([]byte, []int) {
	return file_iam_v1_iam_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateNewApiKeyResponse) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *GenerateNewApiKeyResponse) GetApiSecret() string {
	if x != nil {
		return x.ApiSecret
	}
	return ""
}

func (x *GenerateNewApiKeyResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ValidateApiKeyPermissionRequest struct {
	state         protoimpl.MessageState                     `protogen:"open.v1"`
	ApiKey        string                                     `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	ApiSecret     string                                     `protobuf:"bytes,2,opt,name=api_secret,json=apiSecret,proto3" json:"api_secret,omitempty"`
	Permission    ValidateApiKeyPermissionRequest_Permission `protobuf:"varint,3,opt,name=permission,proto3,enum=iam.v1.ValidateApiKeyPermissionRequest_Permission" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateApiKeyPermissionRequest) Reset() {
	*x = ValidateApiKeyPermissionRequest{}
	mi := &file_iam_v1_iam_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateApiKeyPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateApiKeyPermissionRequest) ProtoMessage() {}

func (x *ValidateApiKeyPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_iam_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateApiKeyPermissionRequest.ProtoReflect.Descriptor instead.
func (*ValidateApiKeyPermissionRequest) Descriptor() ([]byte, []int) {
	return file_iam_v1_iam_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateApiKeyPermissionRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *ValidateApiKeyPermissionRequest) GetApiSecret() string {
	if x != nil {
		return x.ApiSecret
	}
	return ""
}

func (x *ValidateApiKeyPermissionRequest) GetPermission() ValidateApiKeyPermissionRequest_Permission {
	if x != nil {
		return x.Permission
	}
	return ValidateApiKeyPermissionRequest_PERMISSION_STATUS_UNSPECIFIED
}

type ValidateApiKeyPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authorized    bool                   `protobuf:"varint,1,opt,name=authorized,proto3" json:"authorized,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateApiKeyPermissionResponse) Reset() {
	*x = ValidateApiKeyPermissionResponse{}
	mi := &file_iam_v1_iam_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateApiKeyPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateApiKeyPermissionResponse) ProtoMessage() {}

func (x *ValidateApiKeyPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_iam_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateApiKeyPermissionResponse.ProtoReflect.Descriptor instead.
func (*ValidateApiKeyPermissionResponse) Descriptor() ([]byte, []int) {
	return file_iam_v1_iam_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateApiKeyPermissionResponse) GetAuthorized() bool {
	if x != nil {
		return x.Authorized
	}
	return false
}

type AddUserRoleRequest struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	UserId        string                        `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProjectId     string                        `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Role          AddUserRoleRequest_Permission `protobuf:"varint,3,opt,name=role,proto3,enum=iam.v1.AddUserRoleRequest_Permission" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserRoleRequest) Reset() {
	*x = AddUserRoleRequest{}
	mi := &file_iam_v1_iam_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserRoleRequest) ProtoMessage() {}

func (x *AddUserRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_iam_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserRoleRequest.ProtoReflect.Descriptor instead.
func (*AddUserRoleRequest) Descriptor() ([]byte, []int) {
	return file_iam_v1_iam_proto_rawDescGZIP(), []int{4}
}

func (x *AddUserRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddUserRoleRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *AddUserRoleRequest) GetRole() AddUserRoleRequest_Permission {
	if x != nil {
		return x.Role
	}
	return AddUserRoleRequest_PERMISSION_STATUS_UNSPECIFIED
}

type AddUserRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updated       bool                   `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserRoleResponse) Reset() {
	*x = AddUserRoleResponse{}
	mi := &file_iam_v1_iam_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserRoleResponse) ProtoMessage() {}

func (x *AddUserRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_iam_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserRoleResponse.ProtoReflect.Descriptor instead.
func (*AddUserRoleResponse) Descriptor() ([]byte, []int) {
	return file_iam_v1_iam_proto_rawDescGZIP(), []int{5}
}

func (x *AddUserRoleResponse) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

type ValidateUserPermissionRequest struct {
	state         protoimpl.MessageState                   `protogen:"open.v1"`
	UserId        string                                   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProjectId     string                                   `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Role          ValidateUserPermissionRequest_Permission `protobuf:"varint,3,opt,name=role,proto3,enum=iam.v1.ValidateUserPermissionRequest_Permission" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateUserPermissionRequest) Reset() {
	*x = ValidateUserPermissionRequest{}
	mi := &file_iam_v1_iam_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateUserPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateUserPermissionRequest) ProtoMessage() {}

func (x *ValidateUserPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_iam_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateUserPermissionRequest.ProtoReflect.Descriptor instead.
func (*ValidateUserPermissionRequest) Descriptor() ([]byte, []int) {
	return file_iam_v1_iam_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateUserPermissionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateUserPermissionRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ValidateUserPermissionRequest) GetRole() ValidateUserPermissionRequest_Permission {
	if x != nil {
		return x.Role
	}
	return ValidateUserPermissionRequest_PERMISSION_STATUS_UNSPECIFIED
}

type ValidateUserPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authorized    bool                   `protobuf:"varint,1,opt,name=authorized,proto3" json:"authorized,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateUserPermissionResponse) Reset() {
	*x = ValidateUserPermissionResponse{}
	mi := &file_iam_v1_iam_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateUserPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateUserPermissionResponse) ProtoMessage() {}

func (x *ValidateUserPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_iam_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateUserPermissionResponse.ProtoReflect.Descriptor instead.
func (*ValidateUserPermissionResponse) Descriptor() ([]byte, []int) {
	return file_iam_v1_iam_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateUserPermissionResponse) GetAuthorized() bool {
	if x != nil {
		return x.Authorized
	}
	return false
}

var File_iam_v1_iam_proto protoreflect.FileDescriptor

const file_iam_v1_iam_proto_rawDesc = "" +
	"\n" +
	"\x10iam/v1/iam.proto\x12\x06iam.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"m\n" +
	"\x18GenerateNewApiKeyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x19\n" +
	"\bkey_name\x18\x03 \x01(\tR\akeyName\"\x8e\x01\n" +
	"\x19GenerateNewApiKeyResponse\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x1d\n" +
	"\n" +
	"api_secret\x18\x02 \x01(\tR\tapiSecret\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x8c\x02\n" +
	"\x1fValidateApiKeyPermissionRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x1d\n" +
	"\n" +
	"api_secret\x18\x02 \x01(\tR\tapiSecret\x12R\n" +
	"\n" +
	"permission\x18\x03 \x01(\x0e22.iam.v1.ValidateApiKeyPermissionRequest.PermissionR\n" +
	"permission\"]\n" +
	"\n" +
	"Permission\x12!\n" +
	"\x1dPERMISSION_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11PERMISSION_CREATE\x10\x01\x12\x15\n" +
	"\x11PERMISSION_DELETE\x10\x02\"B\n" +
	" ValidateApiKeyPermissionResponse\x12\x1e\n" +
	"\n" +
	"authorized\x18\x01 \x01(\bR\n" +
	"authorized\"\xd3\x01\n" +
	"\x12AddUserRoleRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x129\n" +
	"\x04role\x18\x03 \x01(\x0e2%.iam.v1.AddUserRoleRequest.PermissionR\x04role\"J\n" +
	"\n" +
	"Permission\x12!\n" +
	"\x1dPERMISSION_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PERMISSION_ADMIN_ROLE\x10\x01\"/\n" +
	"\x13AddUserRoleResponse\x12\x18\n" +
	"\aupdated\x18\x01 \x01(\bR\aupdated\"\xe9\x01\n" +
	"\x1dValidateUserPermissionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12D\n" +
	"\x04role\x18\x03 \x01(\x0e20.iam.v1.ValidateUserPermissionRequest.PermissionR\x04role\"J\n" +
	"\n" +
	"Permission\x12!\n" +
	"\x1dPERMISSION_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PERMISSION_ADMIN_ROLE\x10\x01\"@\n" +
	"\x1eValidateUserPermissionResponse\x12\x1e\n" +
	"\n" +
	"authorized\x18\x01 \x01(\bR\n" +
	"authorizedB3Z1github.com/lucas-woo/cloud-drive/api/iam/v1/iamv1b\x06proto3"

var (
	file_iam_v1_iam_proto_rawDescOnce sync.Once
	file_iam_v1_iam_proto_rawDescData []byte
)

func file_iam_v1_iam_proto_rawDescGZIP() []byte {
	file_iam_v1_iam_proto_rawDescOnce.Do(func() {
		file_iam_v1_iam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iam_v1_iam_proto_rawDesc), len(file_iam_v1_iam_proto_rawDesc)))
	})
	return file_iam_v1_iam_proto_rawDescData
}

var file_iam_v1_iam_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_iam_v1_iam_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_iam_v1_iam_proto_goTypes = []any{
	(ValidateApiKeyPermissionRequest_Permission)(0), // 0: iam.v1.ValidateApiKeyPermissionRequest.Permission
	(AddUserRoleRequest_Permission)(0),              // 1: iam.v1.AddUserRoleRequest.Permission
	(ValidateUserPermissionRequest_Permission)(0),   // 2: iam.v1.ValidateUserPermissionRequest.Permission
	(*GenerateNewApiKeyRequest)(nil),                // 3: iam.v1.GenerateNewApiKeyRequest
	(*GenerateNewApiKeyResponse)(nil),               // 4: iam.v1.GenerateNewApiKeyResponse
	(*ValidateApiKeyPermissionRequest)(nil),         // 5: iam.v1.ValidateApiKeyPermissionRequest
	(*ValidateApiKeyPermissionResponse)(nil),        // 6: iam.v1.ValidateApiKeyPermissionResponse
	(*AddUserRoleRequest)(nil),                      // 7: iam.v1.AddUserRoleRequest
	(*AddUserRoleResponse)(nil),                     // 8: iam.v1.AddUserRoleResponse
	(*ValidateUserPermissionRequest)(nil),           // 9: iam.v1.ValidateUserPermissionRequest
	(*ValidateUserPermissionResponse)(nil),          // 10: iam.v1.ValidateUserPermissionResponse
	(*timestamppb.Timestamp)(nil),                   // 11: google.protobuf.Timestamp
}
var file_iam_v1_iam_proto_depIdxs = []int32{
	11, // 0: iam.v1.GenerateNewApiKeyResponse.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: iam.v1.ValidateApiKeyPermissionRequest.permission:type_name -> iam.v1.ValidateApiKeyPermissionRequest.Permission
	1,  // 2: iam.v1.AddUserRoleRequest.role:type_name -> iam.v1.AddUserRoleRequest.Permission
	2,  // 3: iam.v1.ValidateUserPermissionRequest.role:type_name -> iam.v1.ValidateUserPermissionRequest.Permission
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_iam_v1_iam_proto_init() }
func file_iam_v1_iam_proto_init() {
	if File_iam_v1_iam_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iam_v1_iam_proto_rawDesc), len(file_iam_v1_iam_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_iam_v1_iam_proto_goTypes,
		DependencyIndexes: file_iam_v1_iam_proto_depIdxs,
		EnumInfos:         file_iam_v1_iam_proto_enumTypes,
		MessageInfos:      file_iam_v1_iam_proto_msgTypes,
	}.Build()
	File_iam_v1_iam_proto = out.File
	file_iam_v1_iam_proto_goTypes = nil
	file_iam_v1_iam_proto_depIdxs = nil
}
